### ISSUE TITLE
[QUestion] Funciona para conta PJ (Inter PRO)

### ISSUE THREAD

**Issue by nagualcode** [Hamdan85/BoletoIntermedium#1]
Olá, bom dia!
Gostaria de saber se é compatível com PJ (Conta Inter PRO) ?

Obrigado!

**Comment by Hamdan85** [comment]
Cara, ate onde eu sei a montagem de boletos é meio padrão... mas n posso te confirmar porque não fiz  com a documentação da conta PJ... portanto n garanto.
